#- name: Configure sudo access
#  ansible.builtin.copy:
#    dest: "/etc/sudoers.d/{{ item.username }}"
#    content: "{{ item.username }} ALL=(ALL) NOPASSWD:ALL"
#    owner: root
#    group: root
#    mode: '0440'
#  loop: "{{ users }}"
#  when:
#    - item.sudo | default(false)
#    - item.state | default('present') == 'present'
#
#- name: Remove sudo access when user is absent
#  ansible.builtin.file:
#    path: "/etc/sudoers.d/{{ item.username }}"
#    state: absent
#  loop: "{{ users }}"
#  when:
#    - item.state | default('present') == 'absent'

#- name: Configure sudo access
#  ansible.builtin.copy:
#    dest: "/etc/sudoers.d/{{ item.0.username }}"
#    content: "{{ item.0.username }} ALL=(ALL) NOPASSWD:ALL"
#    owner: root
#    group: root
#    mode: '0440'
#  loop: "{{ users | subelements('fleet') }}"
#  when:
#    - item.0.username == inventory_hostname
#    - item.1.sudo | default(false) == 'true'

- name: Configure sudo access
  ansible.builtin.user:
    name: "{{ item.0.username }}"
    groups: sudo
    append: true 
  loop: "{{ users | subelements('fleet') }}"
  when:
    - item.1.hostname == inventory_hostname
    - item.1.sudo | default(false) == true

- name: Remove sudo access
  ansible.builtin.command: "gpasswd -d "{{ item.0.username }}" sudo"
  register: gpasswd_res
#  changed_when: "'is not a member of' not in result.stderr"
  changed_when: "'removing user' in gpasswd_res.stdout or 'Removing user' in gpasswd_res.stdout"
#  failed_when: false  # Prevents failure if the user wasn't in the group
  failed_when: 
      - gpasswd_res.rc != 0 
      - "'is not a member of' not in gpasswd_res.stderr"
  loop: "{{ users | subelements('fleet') }}"
  when:
    - item.1.hostname == inventory_hostname
    - item.1.sudo | default(false) == false

#- name: Remove sudo access
#  ansible.builtin.file:
#    path: "/etc/sudoers.d/{{ item.0.username }}"
#    state: absent
#  loop: "{{ users | subelements('fleet') }}"
#  when:
#    - item.1.hostname == inventory_hostname
#    - item.1.sudo | default(false) == false
