---
# tasks file for roles/user_management
- name: Manage users
  ansible.builtin.user:
    name: "{{ item.username }}"
    state: "{{ item.state | default('present') }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    groups: "{{ item.groups | default(omit) }}"
    append: "{{ item.groups is defined }}"
    password: "{{ item.password | default("1234567890") }}"
  loop: "{{ final_users }}"
  when: item.state == 'present'
# - name: Setup SSH authorized keys
#   ansible.builtin.authorized_key:
#     user: "{{ item.username }}"
#     key: "{{ item.ssh_key }}"
#     state: present
#   loop: "{{ users }}"
#   when:
#     - item.state | default('present') == 'present'
#     - item.ssh_key is defined
