---
# tasks file for roles/user_management
- name: Manage users
  ansible.builtin.user:
    name: "{{ item.0.username }}"
    state: "{{ item.0.state | default('present') }}"
    shell: "{{ item.1.shell | default('/bin/bash') }}"
    groups: "{{ item.0.groups | default(omit) }}"
    append: "{{ item.0.groups is defined }}"
#    password: "{{ item.password | default('1234567890') | password_hash('sha512') }}"
    password: "{{ item.1.password }}"
    update_password: on_create
  loop: "{{ final_users | subelements('fleet') }}"
  when: item.0.state == 'present'

# - name: Setup SSH authorized keys
#   ansible.builtin.authorized_key:
#     user: "{{ item.username }}"
#     key: "{{ item.ssh_key }}"
#     state: present
#   loop: "{{ users }}"
#   when:
#     - item.state | default('present') == 'present'
#     - item.ssh_key is defined
